services:
  app:
    image: ghcr.io/tmiya-tech/20251115_sample-app/todo-app:webflux
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_R2DBC_URL=r2dbc:postgresql://${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/postgres
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - SPRING_R2DBC_POOL_INITIAL_SIZE=${MIN_POOL_SIZE:-10}
      - SPRING_R2DBC_POOL_MIN_IDLE=${MIN_POOL_SIZE:-10}
      - SPRING_R2DBC_POOL_MAX_SIZE=${MAX_POOL_SIZE:-100}
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '${APP_CPUS:-2.0}'
          memory: ${APP_MEMORY:-1G}
