services:
  postgres:
    image: postgres:18
    restart: always
    command: ["postgres", "-c", "max_connections=${POSTGRES_MAX_CONNECTIONS:-200}"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '${POSTGRES_CPUS:-2.0}'
          memory: ${POSTGRES_MEMORY:-2G}
  wiremock:
    image: wiremock/wiremock:3x
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ../../wiremock:/home/wiremock

volumes:
  postgres_data: