spring:
  application:
    name: sample-web
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
  sql:
    init:
      mode: always
  docker:
    compose:
      file:
        - ../docker-compose.yml
      skip:
        in-tests: false

sample.ec:
  backend-base-url: http://localhost:8081