spring:
  application:
    name: sample-web
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
  sql:
    init:
      mode: always

sample.ec:
  backend-base-url: http://localhost:8081